program loopy;
int sum, j, k;
int array[10];
int bigSum;
bigSum = 0;
sum = 0;
for j = 1 to 10;
      for k = 1 to 10;
            sum = sum + 1;
      next
next
if (sum >= 100) then
      bigSum = 10;
      for j = 1 to 10;
            bigSum = bigSum+1;
next endif
if (bigSum < 20) then
      array[0]=1;
      array[1]=2;
      array[2]=3;
      array[3]=4;
      array[4]=5;
      array[5]=6;
      array[6]=7;
      array[7]=8;
      array[8]=9;
      array[9]=10;
endif
stop; end;